--- 
- hosts: "servers"
  tasks: 
    - name: Update
      apt: update_cache=yes force_apt_get=yes cache_valid_time=3600

    - name: Ustanovka
      apt: pkg={{ item }} state=latest
      with_items:
      - curl
    
    - name: Accept to port 80
      community.general.ufw:
        rule: allow
        port: '80'
        proto: tcp

    - name: Accept to port 8080
      community.general.ufw:
        rule: allow
        port: '8080'
        proto: tcp

    - name: Accept to port 1834
      community.general.ufw:
        rule: allow
        port: '1834'
        proto: tcp
   
    - name: UFW
      service:
        name: ufw
        state: started
      retries: 3
      delay: 3 

    - name: port
      ansible.builtin.lineinfile: 
        path: /etc/ssh/sshd_config 
        line: 'Port 1834'
        line: 'PubkeyAuthentication yes'   
        create: yes
    
    - name: Restart
      service:
        name: sshd
        state: restarted

    - name: Restart the server
      reboot: 
         msg: "Reboot initiated by Ansible"
         connect_timeout: 5
         reboot_timeout: 600
         pre_reboot_delay: 0
         post_reboot_delay: 30
         test_command: whoami
